version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: students
      MYSQL_USER: reda
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: reda
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: courses
    ports:
      - "5433:5432"
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer-container
    ports:
      - "8080:8080"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
#      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    depends_on:
      - mysql
    ports:
      - "8181:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
