server:
  port: 8888

spring:
  profiles:
    active: github
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
