server:
  port: 8888

spring:
  profiles:
    active: github
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HIMMIREDA/microservices-exam-config
